In [21]:
using LinearAlgebra
using Plots
using FileIO

In [22]:
# Create symmetric matrix A and take its eigendecomposition
m = 5
A = Symmetric(rand(m,m))
Ae = eigen(A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
5-element Vector{Float64}:
 -0.8162463480402122
 -0.5188272758199919
  0.2718694821052213
  0.7877119773579085
  3.1295283531912834
vectors:
5×5 Matrix{Float64}:
 -0.023622   0.378633   -0.766798   -0.0869349  -0.510433
 -0.26208   -0.812394   -0.0555428  -0.217605   -0.469993
 -0.242495   0.410528    0.510461   -0.627366   -0.344243
  0.860711  -0.0546101   0.234439    0.0658111  -0.443735
 -0.362116   0.15855     0.305619    0.73971    -0.450732

In [23]:
# Check out the norm of one of the eigenvectors
eig_norm = sqrt(Ae.vectors[:,3]'Ae.vectors[:,3])

0.9999999999999999

In [24]:
A

5×5 Symmetric{Float64, Matrix{Float64}}:
 0.906345  0.931793  0.401124   0.682773  0.567511
 0.931793  0.33095   0.727321   0.798958  0.520918
 0.401124  0.727321  0.616297   0.660054  0.0569973
 0.682773  0.798958  0.660054   0.028319  0.942648
 0.567511  0.520918  0.0569973  0.942648  0.972125

In [25]:
# Matrix-level reconstruction of A
Ar = Ae.vectors * Diagonal(Ae.values) * Ae.vectors'

5×5 Matrix{Float64}:
 0.906345  0.931793  0.401124   0.682773  0.567511
 0.931793  0.33095   0.727321   0.798958  0.520918
 0.401124  0.727321  0.616297   0.660054  0.0569973
 0.682773  0.798958  0.660054   0.028319  0.942648
 0.567511  0.520918  0.0569973  0.942648  0.972125

In [26]:
# Vector-level reconstruction of A

layers = []

for ii in 1:m
    layer = Ae.vectors[:,ii] .* Ae.values[ii] * Ae.vectors[:,ii]'
    push!(layers, layer)
end

In [28]:
rebuild = zeros(m,m)

for layer in layers
    rebuild += layer
end

In [29]:
rebuild

5×5 Matrix{Float64}:
 0.906345  0.931793  0.401124   0.682773  0.567511
 0.931793  0.33095   0.727321   0.798958  0.520918
 0.401124  0.727321  0.616297   0.660054  0.0569973
 0.682773  0.798958  0.660054   0.028319  0.942648
 0.567511  0.520918  0.0569973  0.942648  0.972125

In [30]:
# Check out norm of a single layer. It matches the eigenvalue that created it! I mean duh, since ||eigenvector|| = 1
idx = 1
norm = sqrt(tr(layers[idx]'layers[idx]))
println(norm)
println(Ae.values[idx])

0.8162463480402121
-0.8162463480402122
