In [146]:
using LinearAlgebra

In [147]:
m = 3
n = 6
A = rand(m,n)

3×6 Matrix{Float64}:
 0.131078   0.0570004  0.255049  0.495716  0.942103  0.919807
 0.0170428  0.483751   0.157332  0.4263    0.855602  0.269619
 0.395137   0.574704   0.52123   0.876933  0.157132  0.239077

In [148]:
Us, Es, Vs = svd(A, full=true)

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×3 Matrix{Float64}:
 -0.674733   0.544333   0.498434
 -0.52526    0.120276  -0.842399
 -0.518495  -0.830202   0.204762
singular values:
3-element Vector{Float64}:
 1.9718644434302008
 0.8966494815448495
 0.47653799739911984
Vt factor:
6×6 Matrix{Float64}:
 -0.153292  -0.299481  -0.266238  -0.513767   -0.5916     -0.449425
 -0.283994  -0.432622  -0.306666  -0.453826    0.541209    0.373198
  0.276759  -0.548588   0.212611   0.14171    -0.45958     0.588181
 -0.398402  -0.287401  -0.497837   0.703875   -0.0534406  -0.111979
 -0.481381  -0.355295   0.734659   0.0669019   0.13148    -0.283816
 -0.654829   0.461917   0.048004  -0.100439   -0.354607    0.468714

In [149]:
A_val, A_vec = eigen(A'A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
6-element Vector{Float64}:
 -1.6354560136121285e-17
  4.41101357517502e-17
  4.3027445692790084e-16
  0.22708846296516333
  0.8039802927546479
  3.8882493832642906
vectors:
6×6 Matrix{Float64}:
 -0.853431    0.200995    0.224742  -0.276759  -0.283994  -0.153292
 -0.161987   -0.073293   -0.624971   0.548588  -0.432622  -0.299481
  0.0790145  -0.854037    0.232912  -0.212611  -0.306666  -0.266238
  0.468737    0.472417    0.259058  -0.14171   -0.453826  -0.513767
 -0.139489   -0.0408996   0.353212   0.45958    0.541209  -0.5916
  0.0         0.0        -0.559271  -0.588181   0.373198  -0.449425

In [150]:
A_val = sqrt.(round.(A_val[4:n], digits=5))

3-element Vector{Float64}:
 0.4765396101060225
 0.89664931829562
 1.971864599814095

In [164]:
A_vec = A_vec[:,4:6]

6×3 Matrix{Float64}:
 -0.276759  -0.283994  -0.153292
  0.548588  -0.432622  -0.299481
 -0.212611  -0.306666  -0.266238
 -0.14171   -0.453826  -0.513767
  0.45958    0.541209  -0.5916
 -0.588181   0.373198  -0.449425

In [168]:
U = zeros(m,m)

for ii in 1:length(A_val)
    Ai = A * A_vec[:,ii] ./ A_val[ii]
    U[:,ii] = Ai
end

U

3×3 Matrix{Float64}:
 -0.498432   0.544333  -0.674733
  0.842396   0.120276  -0.52526
 -0.204762  -0.830202  -0.518495

In [161]:
Us

3×3 Matrix{Float64}:
 -0.674733   0.544333   0.498434
 -0.52526    0.120276  -0.842399
 -0.518495  -0.830202   0.204762

In [ ]:
V = zeros(n,n)

for ii in 1:length(A_val)
    Ai = A * A_vec[:,ii] ./ A_val[ii]
    U[:,ii] = Ai
end
